USE sakila;

#Retrieve the store ID, city, and country for each store.
SELECT store_id, city, country
FROM store
INNER JOIN address
ON store.address_id = address.address_id
INNER JOIN city
ON address.city_id = city.city_id
INNER JOIN country
ON city.country_id = country.country_id;

#Calculate the total revenue generated by each store in dollars.

SELECT store.store_id, SUM(amount)
FROM store
INNER JOIN staff
ON store.store_id = staff.store_id
INNER JOIN payment
ON staff.staff_id = payment.staff_id
GROUP BY store_id;


#Determine the average running time of films for each category
SELECT name, ROUND(AVG(film.length))
FROM film_category
INNER JOIN category
ON film_category.category_id = category.category_id
INNER JOIN film
ON film.film_id = film_category.film_id
GROUP BY name;



#identify the film categories with the longest average running time.

SELECT name, ROUND(AVG(length))
FROM film_category
INNER JOIN category
ON film_category.category_id = category.category_id
INNER JOIN film
ON film_category.film_id = film.film_id
GROUP BY name;

#Display the top 10 most frequently rented movies in descending order.

SELECT title, COUNT(rental_id)
FROM rental
INNER JOIN inventory
ON rental.inventory_id = inventory.inventory_id
INNER JOIN film
ON inventory.film_id = film.film_id
GROUP BY title
ORDER BY COUNT(rental_id) DESC;

